# LFP_util Module Usage Demonstration

## Package Info
- Version 0.1
- Subpackages:
    - data_manage

## Data Manage

This subpackage is made to better maintain the sleep/wake scoring information of the past animals. It consists of a lite pickle database, two major functions and several helper functions. The idea is to use the "clean data" standard and better support the existing visualization packages.

In [1]:
%load_ext autoreload
%autoreload 2
from LFP_util import data_manage as dm

### Functions

- append
- agg

In [2]:
dir(dm)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'accessor',
 'agg',
 'all_data',
 'append',
 'cache',
 'format',
 'np',
 'pd',
 'pickle',
 'save_new',
 'view_new']

## Agg

- agg function retrieves data of relevant field
- available fields: 'Animal', 'SW_stat', 'Restart_date', 'SW_array'

In [3]:
print(dm.agg.__doc__)

    This function pull data from the database and aggregate them into a dataframe in long form.
    Notice that there might be missing data if the record itself is imcomplete.

    Tip: If a user friendy wide form datafame is desired, use the following example command:
        #to convert SW_stat from long form to wide from
        df.reset_index().pivot(index=['Animal', 'Age'], columns=['State'], values=['percent', 'Bout'])

    Parameter:
    fields: names of the interested fields
            (select from ['Animal', 'SW_stat', 'Restart_date', 'SW_array'])
            If "all" is passed in, all fields would be selected
            Not a list! Strings plz

    Return:
    result: A dataframe of the selected fields;
            None if no fields is selected
    sw_array: (Optional) A list of sleep_wake_state arrays for all restart day;
              Only returned when 'SW_array' is passed as an argument

In [4]:
#Single Field
dm.agg('Animal')

       Genotype   Birthday
Animal
CAF100       WT 2021-03-01
CAF101       WT 2021-03-01
CAF22       TE4 2020-02-17
CAF37       TE4 2019-08-18
CAF42        WT 2020-02-20
CAF48       TE4 2020-07-20
CAF49       TE4 2020-07-20
CAF52       TE4 2020-04-19
CAF60       TE4 2020-09-23
CAF72       TE4 2020-11-24
CAF78       TE4 2020-04-19
CAF82        WT 2019-12-05
CAF84       TE4 2020-08-10
CAF88        WT 2019-12-05
CAF89        WT 2020-07-23
CAF95        WT 2021-01-30
KDR14        WT 2021-08-19
KDR27        WT 2021-11-01
KDR36        WT 2021-11-01

In [5]:
#Multiple Fields
dm.agg('Animal', 'SW_stat')

                 Genotype   Birthday    percent      Bout
Animal Age State
CAF100 57  Wake        WT 2021-03-01  52.842593  2.605936
           NREM        WT 2021-03-01  38.500000  1.866667
           REM         WT 2021-03-01   8.657407  1.133333
CAF101 57  Wake        WT 2021-03-01  53.712963  1.618131
           NREM        WT 2021-03-01  38.578704  1.138388
...                   ...        ...        ...       ...
KDR27  56  NREM        WT 2021-11-01  38.958333  3.169492
           REM         WT 2021-11-01   8.240741  1.223368
KDR36  82  Wake        WT 2021-11-01  53.333333  4.338983
           NREM        WT 2021-11-01  38.976852  3.017563
           REM         WT 2021-11-01   7.689815  1.153472

[81 rows x 4 columns]

In [6]:
#the function return a tuple if SW_array is passed in
r = dm.agg('Animal', 'SW_array')
type(r[0]), type(r[1])

(pandas.core.frame.DataFrame, list)

In [7]:
#get the entire frame
dm.agg('all')[0]

                 Genotype   Birthday    percent      Bout        #MA  \
Animal Age State
CAF100 57  Wake        WT 2021-03-01  52.842593  2.605936   6.333333
           NREM        WT 2021-03-01  38.500000  1.866667   6.333333
           REM         WT 2021-03-01   8.657407  1.133333   6.333333
CAF101 57  Wake        WT 2021-03-01  53.712963  1.618131  13.416667
           NREM        WT 2021-03-01  38.578704  1.138388  13.416667
...                   ...        ...        ...       ...        ...
KDR27  56  NREM        WT 2021-11-01  38.958333  3.169492   8.000000
           REM         WT 2021-11-01   8.240741  1.223368   8.000000
KDR36  82  Wake        WT 2021-11-01  53.333333  4.338983  11.833333
           NREM        WT 2021-11-01  38.976852  3.017563  11.833333
           REM         WT 2021-11-01   7.689815  1.153472  11.833333

                                                           Location  \
Animal Age State
CAF100 57  Wake   /media/HlabShare/Sleep_Scoring/CAF00100_LFP/*S...
           NREM   /media/HlabShare/Sleep_Scoring/CAF00100_LFP/*S...
           REM    /media/HlabShare/Sleep_Scoring/CAF00100_LFP/*S...
CAF101 57  Wake   /media/HlabShare/Sleep_Scoring/CAF00101_LFP/*S...
           NREM   /media/HlabShare/Sleep_Scoring/CAF00101_LFP/*S...
...                                                             ...
KDR27  56  NREM   /media/HlabShare/Sleep_Scoring/KDR00027/*Sleep...
           REM    /media/HlabShare/Sleep_Scoring/KDR00027/*Sleep...
KDR36  82  Wake   /media/HlabShare/Sleep_Scoring/KDR00036/*Sleep...
           NREM   /media/HlabShare/Sleep_Scoring/KDR00036/*Sleep...
           REM    /media/HlabShare/Sleep_Scoring/KDR00036/*Sleep...

                         RestartTime  SW_id
Animal Age State
CAF100 57  Wake  2021-04-27 15:05:44   13.0
           NREM  2021-04-27 15:05:44   13.0
           REM   2021-04-27 15:05:44   13.0
CAF101 57  Wake  2021-04-27 15:05:44   14.0
           NREM  2021-04-27 15:05:44   14.0
...                              ...    ...
KDR27  56  NREM  2021-12-27 10:22:55   16.0
           REM   2021-12-27 10:22:55   16.0
KDR36  82  Wake  2022-01-22 14:49:39   17.0
           NREM  2022-01-22 14:49:39   17.0
           REM   2022-01-22 14:49:39   17.0

[81 rows x 8 columns]

## Append

- Adds a new entry to the existing database

In [3]:
print(dm.append.__doc__)

    Append one one entry at a time. The function automatically formats the dataframe and save it to a temporary cache.

    Parameter:
    entry: A dataframe with only one row that cannot has nan in it
    new_array: the sw_scoring array for this entry

    Return:
    the new dataframe

In [9]:
import pandas as pd
new = pd.DataFrame(
    {
        'Animal': ['CAF69'],
        'Age': [1],
        '%Wake': [.3],
        '%NREM': [.5],
        '%REM': [.2],
        '#MA': [3.33],
        'Wake Bout': [30],
        'NREM Bout': [30],
        'REM Bout': [20],
        'Location': ['123asd'],
        'RestartTime': ['2002-10-30'],
        'hasError': [True],
        'Genotype':['WT'],
        'Birthday':['2002-10-30']
    }
)
array = [1,1,1,1,1]

In [10]:
dm.append(new, array); #returns a dictonary

In [11]:
dm.agg('Animal')

       Genotype             Birthday
Animal
CAF100       WT  2021-03-01 00:00:00
CAF101       WT  2021-03-01 00:00:00
CAF22       TE4  2020-02-17 00:00:00
CAF37       TE4  2019-08-18 00:00:00
CAF42        WT  2020-02-20 00:00:00
CAF48       TE4  2020-07-20 00:00:00
CAF49       TE4  2020-07-20 00:00:00
CAF52       TE4  2020-04-19 00:00:00
CAF60       TE4  2020-09-23 00:00:00
CAF72       TE4  2020-11-24 00:00:00
CAF78       TE4  2020-04-19 00:00:00
CAF82        WT  2019-12-05 00:00:00
CAF84       TE4  2020-08-10 00:00:00
CAF88        WT  2019-12-05 00:00:00
CAF89        WT  2020-07-23 00:00:00
CAF95        WT  2021-01-30 00:00:00
KDR14        WT  2021-08-19 00:00:00
KDR27        WT  2021-11-01 00:00:00
KDR36        WT  2021-11-01 00:00:00
CAF101       WT           2002-10-30

### Properly Save the Results
The append function only stores the modification to temporary cache and nothing is actually saved until the user tell it explicitly.
To save the result to the database, run save_new.

In [12]:
# To save the change
#the actual command is commented out for we dont want to do any change here
#save_new()